"""Magic numbers and limits for ServerPulse Agent."""

API_POST_TIMEOUT = 10
API_GET_TIMEOUT = 10
API_TEMPLATE_TIMEOUT = 30
UPDATE_FETCH_TIMEOUT = 15
SCRIPT_EXEC_TIMEOUT = 300
CONFIG_APPLIER_TIMEOUT = 30
EXTRA_CMD_TIMEOUT = 60

TOP_PROCESS_LIMIT = 10
DISK_MAX_ENTRIES = 50
NETWORK_MAX_ENTRIES = 20

CPU_SNAP_INTERVAL_SEC = 0.2
CPU_HZ_DEFAULT = 100

LOG_MAX_BYTES = 1_048_576
LOG_MAX_BACKUPS = 5

LOCK_MAX_AGE_SECONDS = 120
LOCK_RETRY_SECONDS = 5
LOCK_RETRY_MAX = 3

STATE_ENCODING = "utf-8"
